apiVersion: v1
kind: Service
metadata: 
  name: orders
spec:
  type: NodePort
  selector:
    app: orderservice
  ports:
    - name: orderservice
      protocol: TCP
      port: 80
      targetPort: 80