apiVersion: apps/v1
kind: Deployment
metadata: 
  name: order-depl
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: largescaleproject-orders:latest
          imagePullPolicy: Never