apiVersion: v1
kind: Service
metadata: 
  name: productsservice
spec:
  type: NodePort
  selector:
    app: products
  ports:
    - name: products
      protocol: TCP
      port: 80
      targetPort: 80