name: Build and Push Docker Images 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - name: Auth
            path: ./Auth/
            dockerfile: ./Auth/Dockerfile
            image: mehrdadsn/auth
          - name: ProductProject
            path: ./ProductProject/
            dockerfile: ./ProductProject/Dockerfile
            image: mehrdadsn/product
          - name: OrdersProject
            path: ./OrdersProject/
            dockerfile: ./OrdersProject/Dockerfile
            image: mehrdadsn/order
          - name: PaymentProject
            path: ./PaymentProject/
            dockerfile: ./PaymentProject/Dockerfile
            image: mehrdadsn/payment
          - name: NotificationProject
            path: ./NotificationProject/
            dockerfile: ./NotificationProject/Dockerfile
            image: mehrdadsn/notification

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (if needed for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and push Docker image for each project
      - name: Build and Push Docker Image for ${{ matrix.project.name }}
        run: |
          docker build -f ${{ matrix.project.dockerfile }} -t ${{ matrix.project.image }} ${{ matrix.project.path }}
          docker push ${{ matrix.project.image }}
